import Header from '../components/Header';
import Footer from '../components/Footer';

export default function Privacy() {
  const currentYear = new Date().getFullYear();

  return (
    <>
      <Header />
      <main>
        <section className="max-container text-center" style={{ padding: '60px 0' }}>
          <h2 className="section-header-title mb-4">Privacy Policy</h2>

          <p>
            This website is operated by <strong>Ronel Herzass</strong> and is intended for personal and
            educational purposes.
          </p>

          <p>
            I respect your privacy. This website does not collect personal data unless you contact me
            directly through email or external links such as LinkedIn or GitHub.
          </p>

          <h3 style={{ marginTop: '40px' }}>Use of Google Analytics</h3>
          <p>
            This website uses <strong>Google Analytics</strong>, a web analytics service provided by
            Google LLC. Google Analytics uses cookies—small text files stored on your device—to help
            analyze how visitors use the site. The information generated by these cookies (including your
            IP address, device type, and pages visited) is transmitted to and stored by Google on servers
            in the United States.
          </p>

          <p>
            The data collected is used only to understand general visitor behavior, such as which pages
            are most popular and how visitors find the website. This helps me improve the site's content
            and performance.
          </p>

          <p>
            You can opt out of Google Analytics by installing the{' '}
            <a
              href="https://tools.google.com/dlpage/gaoptout"
              target="_blank"
              rel="noopener"
            >
              Google Analytics Opt-out Browser Add-on
            </a>
            .
          </p>

          <h3 style={{ marginTop: '40px' }}>Contact</h3>
          <p>
            If you have any questions about this Privacy Policy or the data collected, you can contact me
            at:
            <br />
            <a href="mailto:ronelherzass@gmail.com">ronelherzass@gmail.com</a>
          </p>

          <p className="text-gray-600" style={{ marginTop: '30px' }}>
            © {currentYear} Ronel Herzass. All rights reserved.
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}
